// lib/ieltsWords.js
export const IELTS_WORDS = [
  { "id": "ielts_1", "word": "across", "example": "The trend was consistent across all age groups." },
  { "id": "ielts_2", "word": "process", "example": "The process of urbanization is accelerating." },
  { "id": "ielts_3", "word": "recommend", "example": "Experts recommend a reduction in carbon emissions." },
  { "id": "ielts_4", "word": "necessary", "example": "It is necessary to implement stricter regulations." },
  { "id": "ielts_5", "word": "apparent", "example": "The apparent shift in public opinion was unexpected." },
  { "id": "ielts_6", "word": "exaggerate", "example": "The media tends to exaggerate the risks." },
  { "id": "ielts_7", "word": "occasion", "example": "On this occasion, the figures remained stable." },
  { "id": "ielts_8", "word": "parallel", "example": "The two lines on the graph run parallel." },
  { "id": "ielts_9", "word": "immediate", "example": "Technology provides immediate access to information." },
  { "id": "ielts_10", "word": "address", "example": "The government must address the housing crisis." },
  { "id": "ielts_11", "word": "assess", "example": "Tutors assess students based on their coursework." },
  { "id": "ielts_12", "word": "accommodation", "example": "Student accommodation is often expensive." },
  { "id": "ielts_13", "word": "possess", "example": "Graduates possess the skills needed for the job." },
  { "id": "ielts_14", "word": "success", "example": "Economic success depends on innovation." },
  { "id": "ielts_15", "word": "occurrence", "example": "Natural disasters are a frequent occurrence." },
  { "id": "ielts_16", "word": "dropped", "example": "The birth rate dropped significantly in 2010." },
  { "id": "ielts_17", "word": "dropping", "example": "Sales have been dropping since last quarter." },
  { "id": "ielts_18", "word": "bigger", "example": "The impact was bigger than previously thought." },
  { "id": "ielts_19", "word": "biggest", "example": "This represents the biggest increase on the chart." },
  { "id": "ielts_20", "word": "running", "example": "The cost of running the program is high." },
  { "id": "ielts_21", "word": "runner", "example": "He was the front runner in the election." },
  { "id": "ielts_22", "word": "beginning", "example": "The data shows a rise at the beginning of the year." },
  { "id": "ielts_23", "word": "beginner", "example": "The course is suitable for a beginner." },
  { "id": "ielts_24", "word": "regretted", "example": "The decision was later regretted by the board." },
  { "id": "ielts_25", "word": "regretting", "example": "Many are now regretting the lack of investment." },
  { "id": "ielts_26", "word": "absence", "example": "The absence of evidence does not mean failure." },
  { "id": "ielts_27", "word": "difference", "example": "There is a notable difference between the two groups." },
  { "id": "ielts_28", "word": "beneficial", "example": "Remote work can be beneficial for productivity." },
  { "id": "ielts_29", "word": "influential", "example": "Social media is an influential tool in marketing." },
  { "id": "ielts_30", "word": "maintenance", "example": "The maintenance of infrastructure is vital." },
  { "id": "ielts_31", "word": "pronunciation", "example": "Clear pronunciation is essential for the Speaking test." },
  { "id": "ielts_32", "word": "exceed", "example": "The costs are likely to exceed the budget." },
  { "id": "ielts_33", "word": "succeed", "example": "Few companies succeed without a digital strategy." },
  { "id": "ielts_34", "word": "environment", "example": "Pollution is damaging the natural environment." },
  { "id": "ielts_35", "word": "government", "example": "The government is investing in renewable energy." },
  { "id": "ielts_36", "word": "autumn", "example": "The survey was conducted in late autumn." },
  { "id": "ielts_37", "word": "column", "example": "The vertical column represents the percentage." },
  { "id": "ielts_38", "word": "conscious", "example": "Consumers are becoming more health-conscious." },
  { "id": "ielts_39", "word": "discipline", "example": "Academic discipline is required for research." },
  { "id": "ielts_40", "word": "science", "example": "Advancements in science have changed medicine." },
  { "id": "ielts_41", "word": "excited", "example": "Students are excited about the exchange program." },
  { "id": "ielts_42", "word": "exception", "example": "With the exception of 2015, prices rose steadily." },
  { "id": "ielts_43", "word": "know", "example": "We know that education reduces poverty." },
  { "id": "ielts_44", "word": "knee", "example": "The athlete suffered a knee injury." },
  { "id": "ielts_45", "word": "eighth", "example": "The eighth chapter discusses the results." },
  { "id": "ielts_46", "word": "twelfth", "example": "It ranks twelfth in terms of population." },
  { "id": "ielts_47", "word": "lose", "example": "Companies may lose their competitive edge." },
  { "id": "ielts_48", "word": "loose", "example": "The data shows a loose connection between the variables." },
  { "id": "ielts_49", "word": "affect", "example": "Rising temperatures affect crop yields." },
  { "id": "ielts_50", "word": "effect", "example": "The main effect of the policy was positive." },
  { "id": "ielts_51", "word": "complement", "example": "Practical work should complement theory." },
  { "id": "ielts_52", "word": "compliment", "example": "The supervisor gave him a compliment on his essay." },
  { "id": "ielts_53", "word": "its", "example": "The company increased its market share." },
  { "id": "ielts_54", "word": "it's", "example": "It's often argued that technology isoloates people." },
  { "id": "ielts_55", "word": "passed", "example": "The law was passed by the parliament." },
  { "id": "ielts_56", "word": "past", "example": "In the past, communication was much slower." },
  { "id": "ielts_57", "word": "principal", "example": "The principal reason for the change was cost." },
  { "id": "ielts_58", "word": "principle", "example": "Equality is a fundamental principle." },
  { "id": "ielts_59", "word": "than", "example": "The figure was higher than expected." },
  { "id": "ielts_60", "word": "then", "example": "The price peaked and then fell sharply." },
  { "id": "ielts_61", "word": "their", "example": "Many people value their privacy." },
  { "id": "ielts_62", "word": "there", "example": "There are several ways to solve the problem." },
  { "id": "ielts_63", "word": "they're", "example": "They're likely to experience more growth." },
  { "id": "ielts_64", "word": "costume", "example": "The museum displays traditional costumes." },
  { "id": "ielts_65", "word": "custom", "example": "It is a local custom to exchange gifts." },
  { "id": "ielts_66", "word": "hierarchy", "example": "The corporate hierarchy is very rigid." },
  { "id": "ielts_67", "word": "entrepreneur", "example": "A successful entrepreneur takes calculated risks." },
  { "id": "ielts_68", "word": "definitely", "example": "Urbanization will definitely continue to rise." },
  { "id": "ielts_69", "word": "foreign", "example": "Tourism is a major source of foreign income." },
  { "id": "ielts_70", "word": "grateful", "example": "The local community was grateful for the aid." },
  { "id": "ielts_71", "word": "perseverance", "example": "Learning a language requires perseverance." },
  { "id": "ielts_72", "word": "rhythm", "example": "Cities have a fast-paced rhythm of life." },
  { "id": "ielts_73", "word": "Wednesday", "example": "The lecture is scheduled for Wednesday." },
  { "id": "ielts_74", "word": "February", "example": "The coldest month recorded was February." },
  { "id": "ielts_75", "word": "forty", "example": "Nearly forty percent of the population is urban." },
  { "id": "ielts_76", "word": "ninth", "example": "Agriculture is the ninth largest sector." },
  { "id": "ielts_77", "word": "business", "example": "International business is highly competitive." },
  { "id": "ielts_78", "word": "restaurant", "example": "The service industry includes restaurants." },
  { "id": "ielts_79", "word": "committee", "example": "The ethics committee approved the study." },
  { "id": "ielts_80", "word": "tomorrow", "example": "Future projections for tomorrow's climate are bleak." },
  { "id": "ielts_81", "word": "professor", "example": "The professor specialized in biochemistry." },
  { "id": "ielts_82", "word": "embarrass", "example": "Mistakes in public speaking can embarrass people." },
  { "id": "ielts_83", "word": "until", "example": "The trend continued until the end of the decade." },
  { "id": "ielts_84", "word": "argument", "example": "A strong argument can be made for subsidizing solar power." },
  { "id": "ielts_85", "word": "successful", "example": "The pilot project was highly successful." },
  { "id": "ielts_86", "word": "conscientious", "example": "Conscientious students tend to get higher scores." },
  { "id": "ielts_87", "word": "convenience", "example": "Online shopping offers great convenience." },
  { "id": "ielts_88", "word": "independent", "example": "Researchers should remain independent from sponsors." },
  { "id": "ielts_89", "word": "appearance", "example": "The physical appearance of the city changed." },
  { "id": "ielts_90", "word": "resistance", "example": "There was some resistance to the new tax." },
  { "id": "ielts_91", "word": "attendance", "example": "School attendance has improved recently." },
  { "id": "ielts_92", "word": "experience", "example": "Work experience is valued by employers." },
  { "id": "ielts_93", "word": "existence", "example": "The existence of a correlation was proven." },
  { "id": "ielts_94", "word": "calendar", "example": "The academic calendar starts in September." },
  { "id": "ielts_95", "word": "category", "example": "Each category in the pie chart is labeled." },
  { "id": "ielts_96", "word": "cemetery", "example": "The old cemetery is a historical landmark." },
  { "id": "ielts_97", "word": "colleague", "example": "I collaborated on the paper with a colleague." },
  { "id": "ielts_98", "word": "consensus", "example": "There is no consensus on the cause of the problem." },
  { "id": "ielts_99", "word": "equipment", "example": "Laboratory equipment must be handled carefully." },
  { "id": "ielts_100", "word": "gauge", "example": "Surveys are used to gauge public opinion." },
  { "id": "ielts_101", "word": "guarantee", "example": "Higher education does not guarantee a high salary." },
  { "id": "ielts_102", "word": "harass", "example": "Stricter laws prevent people from being harassed." },
  { "id": "ielts_103", "word": "height", "example": "The height of the bar graph shows the frequency." },
  { "id": "ielts_104", "word": "humorous", "example": "The speaker used humorous anecdotes." },
  { "id": "ielts_105", "word": "ignorance", "example": "Ignorance of the law is no excuse." },
  { "id": "ielts_106", "word": "intelligence", "example": "Artificial intelligence is a growing field." },
  { "id": "ielts_107", "word": "jewelry", "example": "Luxury goods include watches and jewelry." },
  { "id": "ielts_108", "word": "leisure", "example": "Leisure activities are important for mental health." },
  { "id": "ielts_109", "word": "license", "example": "You need a license to practice pharmacy." },
  { "id": "ielts_110", "word": "lightning", "example": "Lightning strikes can cause forest fires." },
  { "id": "ielts_111", "word": "maneuver", "example": "The car was able to maneuver through traffic." },
  { "id": "ielts_112", "word": "medieval", "example": "The course covers medieval history." },
  { "id": "ielts_113", "word": "mischievous", "example": "The mischievous behavior of youth was noted." },
  { "id": "ielts_114", "word": "neighbor", "example": "Sudan is a neighbor to several countries." },
  { "id": "ielts_115", "word": "noticeable", "example": "There was a noticeable increase in temperature." },
  { "id": "ielts_116", "word": "possession", "example": "Land possession is a sensitive issue." },
  { "id": "ielts_117", "word": "privilege", "example": "Access to clean water is a right, not a privilege." },
  { "id": "ielts_118", "word": "receipt", "example": "Please keep your receipt for the refund." },
  { "id": "ielts_119", "word": "relevant", "example": "Candidates should highlight relevant experience." },
  { "id": "ielts_120", "word": "religious", "example": "Many festivals have a religious origin." },
  { "id": "ielts_121", "word": "separate", "example": "Data was collected from two separate groups." },
  { "id": "ielts_122", "word": "sufficient", "example": "The evidence provided was sufficient." },
  { "id": "ielts_123", "word": "threshold", "example": "The income threshold for tax was raised." },
  { "id": "ielts_124", "word": "vacuum", "example": "A political vacuum was created after the election." },
  { "id": "ielts_125", "word": "weather", "example": "Extreme weather events are becoming more common." },
  { "id": "ielts_126", "word": "believe", "example": "Many believe that the internet has improved life." },
  { "id": "ielts_127", "word": "relief", "example": "International aid provided relief to the victims." },
  { "id": "ielts_128", "word": "thief", "example": "Identity theft is a modern crime." },
  { "id": "ielts_129", "word": "field", "example": "The field of biochemistry is expanding." },
  { "id": "ielts_130", "word": "piece", "example": "The final piece of the puzzle was found." },
  { "id": "ielts_131", "word": "chief", "example": "The chief cause of pollution is transport." },
  { "id": "ielts_132", "word": "brief", "example": "This essay provides a brief overview." },
  { "id": "ielts_133", "word": "friend", "example": "Close friends can influence our decisions." },
  { "id": "ielts_134", "word": "receive", "example": "Students receive feedback on their work." },
  { "id": "ielts_135", "word": "deceive", "example": "Advertising can sometimes deceive consumers." },
  { "id": "ielts_136", "word": "ceiling", "example": "There is a glass ceiling for women in some industries." },
  { "id": "ielts_137", "word": "perceive", "example": "How people perceive risk varies by culture." },
  { "id": "ielts_138", "word": "conceive", "example": "It is difficult to conceive of a world without cars." }
];
